// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVacantionManager.Data;

#nullable disable

namespace WebVacantionManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b4d5e8fa-7d76-4ff9-95f1-1f1f3a52c111",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3a310333-c4a5-4457-9065-a861e635d848",
                            Name = "Ceo",
                            NormalizedName = "CEO"
                        },
                        new
                        {
                            Id = "96554597-d11d-48bb-84d5-bbf7442a7afc",
                            Name = "Developer",
                            NormalizedName = "DEVELOPER"
                        },
                        new
                        {
                            Id = "e3233cd7-132a-45ca-8a32-7160411726ed",
                            Name = "Unassigned",
                            NormalizedName = "UNASSIGNED"
                        },
                        new
                        {
                            Id = "dd504816-18f8-420f-a69f-ca3e6386ba5c",
                            Name = "TeamLead",
                            NormalizedName = "TEAMLEAD"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1f1a1111-1111-1111-1111-111111111111",
                            RoleId = "3a310333-c4a5-4457-9065-a861e635d848"
                        },
                        new
                        {
                            UserId = "2f2b2222-2222-2222-2222-222222222222",
                            RoleId = "dd504816-18f8-420f-a69f-ca3e6386ba5c"
                        },
                        new
                        {
                            UserId = "3f3c3333-3333-3333-3333-333333333333",
                            RoleId = "96554597-d11d-48bb-84d5-bbf7442a7afc"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebVacantionManager.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1f1a1111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "67658fab-3326-4b74-875a-62b75e6ab1de",
                            Email = "ceo@company.com",
                            EmailConfirmed = true,
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "CEO@COMPANY.COM",
                            NormalizedUserName = "CEO@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOmkoGB1TJ+Dce4kkhbW8cWdaSneJp7VwU4H4MLP7uYhBsMa1ZGWos6fU+59VS38Tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9bd84838-8797-4890-8486-835d75a855d9",
                            TwoFactorEnabled = false,
                            UserName = "ceo@company.com"
                        },
                        new
                        {
                            Id = "2f2b2222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a77cf355-120b-4a78-80cc-15d7f766e38f",
                            Email = "teamlead@company.com",
                            EmailConfirmed = true,
                            FirstName = "Maria",
                            LastName = "Ivanova",
                            LockoutEnabled = false,
                            NormalizedEmail = "TEAMLEAD@COMPANY.COM",
                            NormalizedUserName = "TEAMLEAD@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMbiJVk9fJQsJ6fV8TzSy89cC9w4yWNXV+bLEQbXHC2jUUb5+D9YYxxQiPi1H+YuQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75f85684-32eb-49bb-a653-7ff9ea041f06",
                            TeamId = 1,
                            TwoFactorEnabled = false,
                            UserName = "teamlead@company.com"
                        },
                        new
                        {
                            Id = "3f3c3333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7936acd-87b5-473f-b62b-428540187062",
                            Email = "developer@company.com",
                            EmailConfirmed = true,
                            FirstName = "Georgi",
                            LastName = "Dimitrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEVELOPER@COMPANY.COM",
                            NormalizedUserName = "DEVELOPER@COMPANY.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDVY7B17VbYKWhK5kW0jXmnI0yeM71Am+8Jo99aeBRvc1vqjWZGubMKqT7p7QjbiuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc1199ff-17af-4ffa-a58b-e06cd3775595",
                            TeamId = 1,
                            TwoFactorEnabled = false,
                            UserName = "developer@company.com"
                        });
                });

            modelBuilder.Entity("WebVacantionManager.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4800)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "System for managing students, teachers and courses.",
                            ProjectName = "School Management System"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Application for tracking tasks, deadlines and productivity.",
                            ProjectName = "Task Tracker"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Web platform for booking tables and managing reservations.",
                            ProjectName = "Restaurant Reservation System"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Application that tracks workouts, calories and progress.",
                            ProjectName = "Fitness Tracker"
                        });
                });

            modelBuilder.Entity("WebVacantionManager.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TeamLeaderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamLeaderId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 3,
                            TeamName = "Backend Team"
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 4,
                            TeamName = "Frontend Team"
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 5,
                            TeamName = "Mobile Team"
                        });
                });

            modelBuilder.Entity("WebVacationManager.Models.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("bit");

                    b.Property<int>("VacationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("VacationRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantId = "3f3c3333-3333-3333-3333-333333333333",
                            CreatedOn = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFrom = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            IsHalfDay = false,
                            VacationType = 0
                        },
                        new
                        {
                            Id = 2,
                            ApplicantId = "2f2b2222-2222-2222-2222-222222222222",
                            CreatedOn = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFrom = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            IsHalfDay = true,
                            VacationType = 1
                        },
                        new
                        {
                            Id = 3,
                            ApplicantId = "3f3c3333-3333-3333-3333-333333333333",
                            CreatedOn = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFrom = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = true,
                            IsHalfDay = false,
                            VacationType = 2
                        },
                        new
                        {
                            Id = 4,
                            ApplicantId = "1f1a1111-1111-1111-1111-111111111111",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFrom = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateTo = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsApproved = false,
                            IsHalfDay = false,
                            VacationType = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebVacantionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebVacantionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebVacantionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebVacantionManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebVacantionManager.Models.AppUser", b =>
                {
                    b.HasOne("WebVacantionManager.Models.Team", "Team")
                        .WithMany("Developers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebVacantionManager.Models.Team", b =>
                {
                    b.HasOne("WebVacantionManager.Models.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId");

                    b.HasOne("WebVacantionManager.Models.AppUser", "TeamLeader")
                        .WithMany()
                        .HasForeignKey("TeamLeaderId");

                    b.Navigation("Project");

                    b.Navigation("TeamLeader");
                });

            modelBuilder.Entity("WebVacationManager.Models.VacationRequest", b =>
                {
                    b.HasOne("WebVacantionManager.Models.AppUser", "Applicant")
                        .WithMany("VacationRequests")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("WebVacantionManager.Models.AppUser", b =>
                {
                    b.Navigation("VacationRequests");
                });

            modelBuilder.Entity("WebVacantionManager.Models.Project", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("WebVacantionManager.Models.Team", b =>
                {
                    b.Navigation("Developers");
                });
#pragma warning restore 612, 618
        }
    }
}
